version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "/entrypoint.sh"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./:/auth
    ports:
      - '8000:8000'

  mongodb:
    image: mongo:4.4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data: